cursos/urls.py
from django.contrib import admin
from django.urls import path
from . import views
 
app_name='cursos'
urlpatterns = [
    path('', views.index, name='home'),
    path('area-do-estudante/', views.area_do_estudante, name='area_do_estudante'),
    path('editar-cadastro/', views.editar_cadastro, name='editar_cadastro'),
    path('editar-senha/', views.alterar_senha, name='alterar_senha'),
    path('editar-cadastro-pessoa/', views.editar_cadastro_pessoa, name='editar_cadastro_pessoa'),
    path('atividade/cevest/', views.cursos_cevest, name="cursos_cevest"),            
    path('atividade/cursos/', views.cursos, name="cursos"),            
    path('atividade/<tipo>/<filtro>', views.cursos_filtrado, name="filtrar"),            
    path('atividade/<tipo>/<id>/detalhe', views.curso_detalhe, name="curso_detalhe"),            
    path('atividade/<tipo>/<id>/matricular', views.matricular, name="matricula"),   
             
    # path('prematricula/', views.prematricula, name="prematricula"),
    path('ensino-superior/', views.ensino_superior, name="ensino_superior"),
    path('ensino-tecnico/', views.ensino_tecnico, name="ensino_tecnico"),
    path('curriculo-vitae/', views.curriculo_vitae, name="curriculo_vitae"),
    path('exportar_excel/', views.exportar_para_excel, name='exportar_excel'),
    path('exportar_excel/por-turma/', views.exportar_para_excel_por_turma, name='exportar_excel_por_turma'),

    path('cidade-inteligente/', views.cidade_inteligente_home, name='cidade_inteligente'),
    path('cidade-inteligente/cadastro-camera/', views.cidade_inteligente_cadastro_camera, name='cidade_inteligente_cadastro_camera'),
]

estagio/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'estagio'
urlpatterns = [
    path('', views.index, name= 'index'),
    # path('vagas/', views.vagas, name='vagas'),
    path('vagas/', views.listar_instituicoes, name='vagas'),
    path('vagas/<id>/', views.listar_cursos_e_locais, name='listar_cursos_e_locais'),
    
    path('getLocais/<id>/', views.getLocais, name='get_locais'),
    path('getVagas/<id>/', views.getVagas, name='get_vagas'),
    path('getCursos/<id>/', views.getCursos, name='get_cursos'),
    
    path('area-do-estudante/', views.area_do_estudante, name='area_do_estudante'),
    path('area-da-universidade/', views.area_da_universidade, name='area_da_universidade'),
    path('area-do-estudante/processo/156f165f1<id>4f654f', views.processo_da_vaga, name='processo_da_vaga'),
    path('area-do-estudante/processo/156f165f1<id>4f654f/anexar-tce/', views.anexar_tce, name='anexar_tce'),
    path('area-do-estudante/processo/156f165f1<id>4f654f/vizualiar-tce/', views.visualizar_tce, name='visualizar_tce'),
    
    path('adm/', views.adm, name='adm'),
    path('vagas/cadastrar/', views.cadastro_vaga, name='cadastro_vaga'),
    path('vagas/<id>/<id_curso>/canditar-se/', views.candidatar_se_vaga, name='candidatar_se_vaga'),
    path('candidato/', views.listar_candidato, name='candidato'),
    path('estagiario/', views.listar_estagiario, name='estagiario'),
    path('adm/processo/156f165f1<id>4f654f/', views.adm_processo_da_vaga, name='adm_processo_da_vaga'),
    path('candidato/<id>/editar/', views.editar_estudante, name='editar_candidato'),
    path('candidato/<id>/editar/gerar-processo', views.editar_estudante_processo, name='editar_candidato_processo'),
    path('universidade/', views.listar_universidade, name='listar_universidade'),
    path('universidade/cadastrar_universidade/', views.cadastrar_universidade, name="cadastrar_universidade"),
    path('universidade/<id>/cadastrar_curso', views.cadastrar_curso, name='cadastrar_curso'),
    path('universidade/<id>/curso', views.listar_curso, name='curso'),
    path('universidade/<id>/editar', views.editar_curso, name='editar_curso'),
    path('supervisor/', views.listar_supervisor, name='listar_supervisor'),
    path('supervisor/cadastrar_supervisor', views.cadastrar_supervisor, name='cadastrar_supervisor'),
    path('supervisor/<id>/editar', views.editar_supervisor, name='editar_supervisor'),
    path('secretaria/', views.listar_secretaria, name='listar_secretaria'),
    path('secretaria/<id>/locais/', views.listar_secretaria_locais, name='listar_secretaria_locais'),
    path('secretaria/cadastrar_secretaria', views.cadastrar_secretaria, name='cadastrar_secretaria'),
    path('secretaria/<id>/cadastrar_local', views.cadastrar_local, name='cadastrar_local'),
    path('secretaria/<id>/locais/detalhes/<id_local>', views.locais_detalhes, name="listar_detalhes_do_local"),
    path('secretaria/<id>/locais/detalhes/<id_local>/adicionar-ou-remover', views.locais_detalhes_adicionar_ou_remover, name="listar_detalhes_do_local_add_ou_rmv"),    
    path('adm/vagas/', views.listar_vagas, name='listar_vagas'),
    path('adm/vagas/cadastrar', views.cadastrar_vagas, name='cadastrar_vagas'),
    path('adm/vagas/<id>/editar', views.editar_vagas, name='editar_vagas'),
    path('get_courses_by_university/<university_id>', views.get_courses_by_university, name='get_courses_by_university'),

]

settings/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('autenticacao.urls')),
    path('', include('cursos.urls')),
    # path('capacitacao-profissional/palestras/', include(('palestras.urls', 'palestras'), namespace ='palestras')),

    path('servicos/cevest/', include('cevest_os.urls')),
    path('cevest/almoxarifado/', include('cevest_almoxarifado.urls')),
    path('estagio/', include('estagio.urls')),

    path('administracao/', include('administracao.urls')),    
    path('admin/', admin.site.urls),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cursos/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http import Http404

from autenticacao.functions import aluno_required
from .models import *
from .forms import *
from datetime import date, datetime

from .models import *
from .forms import *
from autenticacao.forms import Form_Pessoa, Form_Alterar_Pessoa
from django.apps import apps
from random import shuffle


from django.urls import reverse

def index(request):
    try:
        eventos = Evento.objects.filter(app_name='cursos', is_destaque = True)
    except:
        eventos=[]
    
    cursos = list(Curso.objects.filter(tipo='C', ativo=True).order_by('?')[:9])
    palestras = list(Curso.objects.filter(tipo='P', ativo=True).order_by('?')[:4])
    shuffle(cursos)
    context = { 
        'titulo': apps.get_app_config('cursos').verbose_name +' - Página Inicial',
        'eventos': eventos,
        'cursos': cursos,   
        'cursos_en': Curso_Ensino_Superior.objects.all()[:4],
        'palestras': palestras 
    }

    return render(request, 'cursos/index.html', context)


def cidade_inteligente_home(request):
    clima = ClimaTempo.objects.first()
    context = {
        'titulo': 'Ciência e Tecnologia - Cidade Inteligente',
        'clima': clima
    }
    return render(request, 'cidade_inteligente.html', context)

@login_required
def cidade_inteligente_cadastro_camera(request):
    clima = ClimaTempo.objects.first()
    if request.method == 'POST':
        form = Solicitacao_de_cadastro_de_cameraForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Solicitação de cadastro de câmera enviada com sucesso!')
            return redirect('cidade_inteligente_cadastro_camera')
    else:
        pessoa = Pessoa.objects.get(user=request.user)
        form = Solicitacao_de_cadastro_de_cameraForm(initial={'pessoa': pessoa})
    context = {
        'titulo': 'Ciência e Tecnologia - Cidade Inteligente',
        'clima': clima,
        'form': form
    }
    return render(request, 'cadastro_camera.html', context)

def cursos(request):
    form = Aluno_form()
    categorias = Categoria.objects.all()
    
    cursos=Curso.objects.filter(tipo='C', ativo=True)

    context = {
        'categorias':categorias,
        'cursos': cursos,
        'form': form,
        'titulo': apps.get_app_config('cursos').verbose_name + ' - ' + 'Cursos',        
        'tipo':'cursos'
    }
    return render(request, 'cursos/cursos.html', context)


def cursos_cevest(request):
    form = Aluno_form()
    categorias = Categoria.objects.all()

    cursos=Curso.objects.filter(tipo='C', categoria__nome='CEVEST', ativo=True)    

    context = {
        'categorias':categorias,
        'cursos': cursos,
        'form': form,
        'titulo': apps.get_app_config('cursos').verbose_name + ' - ' + 'CEVEST',        
        'tipo': 'cevest'
    }
    
    return render(request, 'cursos/cursos.html', context)

def cursos_filtrado(request, tipo, filtro):
    form = Aluno_form()
    categorias = Categoria.objects.all()
    cursos = []
    if tipo == 'cursos':       
       cursos=Curso.objects.filter(tipo='C', categoria__nome=filtro, ativo=True)
    elif tipo == 'palestras':                
        cursos=Curso.objects.filter(tipo='P', categoria__nome=filtro, ativo=True)

    context = {
        'categorias': categorias,
        'cursos': cursos,
        'form': form,
        'titulo': apps.get_app_config('cursos').verbose_name + ' - ' + tipo.capitalize(), 
        'filtro': filtro,
        'tipo': tipo
    }
    if tipo == 'cursos':
        return render(request, 'cursos/cursos.html', context)
    elif tipo == 'palestras':  
        return render(request, 'cursos/palestras.html', context)
    raise Http404("Página não encontrada")

def curso_detalhe(request, tipo, id):    
    curso=Curso.objects.get(id=id)    
    context={
        'curso': curso,
        'tipo': tipo,
        'titulo': apps.get_app_config('cursos').verbose_name+' - Detalhes',
        'turmas': Turma.objects.filter(curso=curso)
    }
    return render(request, 'cursos/curso_detalhe.html', context)

@login_required
def candidatar(request, id):

    curso = Curso.objects.get(id=id)
    form = Aluno_form(initial={'curso': curso})
    if request.method == 'POST':
        form = Aluno_form(request.POST)
        if form.is_valid():
            form.save()

    context = {
        'form': form,
        'titulo': apps.get_app_config('cursos').verbose_name + ' - Inscrição - ' + curso.nome,
    }
    return render(request, 'cursos/cadastrar_candidato.html', context)


def prematricula(request):
    form = Aluno_form(prefix="candidato")
    form_responsavel = CadastroResponsavelForm(prefix="responsavel")

    categorias = Categoria.objects.all()
    cursos = []

    for i in categorias:
        cursos.append(
            {'categoria': i, 'curso': Curso.objects.filter(categoria=i, ativo=True)})

    if request.method == 'POST':
        dtnascimento_cp = request.POST.get("candidato-dt_nascimento")
        form = Aluno_form(request.POST, prefix="candidato")
        form_responsavel = CadastroResponsavelForm(
            request.POST, prefix="responsavel")

        try:
            dtnascimento_hr = datetime.strptime(dtnascimento_cp, "%d-%m-%Y")
        except:
            dtnascimento_hr = datetime.strptime(dtnascimento_cp, "%Y-%m-%d")

        dt_nascimento = dtnascimento_hr.date()

        today = date.today()
        age = today.year - dt_nascimento.year - \
            ((today.month, today.day) < (dt_nascimento.month, dt_nascimento.day))
        teste = True
        candidato = False

        try:
            cpf = request.POST['cpf']
            candidato = Aluno.objects.get(cpf=cpf)
        except Exception as e:
            pass

        if candidato:        
            turma = Turma.objects.get(id=i)
            if candidato:
                try:
                    Matricula.objects.get(
                        candidato=candidato, turma__curso=turma.curso)
                    messages.error(
                        request, 'Candidato já matriculado no curso ' + turma.curso.nome)
                    return redirect('cursos:curso_detalhe')
                except:
                    pass

            if (turma.idade_minima is not None and age < turma.idade_minima) or (turma.idade_maxima is not None and age > turma.idade_maxima):
                teste = False

        if form.is_valid() and teste:
            candidato = form.save(commit=False)

            if age < 18:

                if form_responsavel.is_valid():

                    responsavel = form_responsavel.save(commit=False)
                    responsavel.aluno = candidato

                else:
                    return redirect('cursos:curso_detalhe')

                responsavel.save()
                candidato.save()

            else:

                candidato.save()

            for i in request.POST.getlist('turmas'):
                Matricula.objects.create(
                    aluno=candidato, turma=turma, status='c')

            messages.success(
                request, 'Pré-inscrição realizada com sucesso! Aguarde nosso contato para finalizar inscrição.')
            return redirect('/')
        else:
            if not teste:
                messages.error(
                    request, 'Não foi possível realizar a inscrição na turma: A idade não atende a faixa etária da turma.')
                return redirect('/prematricula')

    context = {
        'form': form,
        'form_responsavel': form_responsavel,
        'categorias': cursos,
        'titulo': apps.get_app_config('cursos').verbose_name + ' - 001',
    }
    return render(request, 'cursos/pre_matricula.html', context)

def alterarCad(request):
    return render(request, 'cursos/alterar_cad.html')


def resultado(request):
    return render(request, 'cursos/resultado.html')

@login_required
def matricular(request, tipo, id):
    curso=Curso.objects.get(id=id)
    pessoa=Pessoa.objects.get(user=request.user)

    #checa se já é aluno para por informações no formulario
    try:
        aluno=Aluno.objects.get(pessoa=pessoa)
        form = Aluno_form(prefix="candidato", instance=aluno)
        try:            
            form_responsavel = CadastroResponsavelForm(prefix="responsavel", instance=aluno)
        except:
            pass
    except Exception as E:        
        aluno=None     
        form = Aluno_form(prefix="candidato")    
        form_responsavel = CadastroResponsavelForm(prefix="responsavel")

    # Checa a idade e se precisa de responsavel
    dtnascimento = pessoa.dt_nascimento    
    today = date.today()
    age = today.year - dtnascimento.year - \
            ((today.month, today.day) < (dtnascimento.month, dtnascimento.day))    
    # precisa_responsavel=age<18
    precisa_responsavel=False
    
    if request.method == 'POST':
        
        form = Aluno_form(request.POST, prefix="candidato", instance=aluno)
        if precisa_responsavel:
            form_responsavel = CadastroResponsavelForm(
                request.POST, prefix="responsavel", instance=aluno)

        
        teste = True        
        
        candidato = aluno
        

        #checando idade minima e maxima para o curso
        turmas=Turma.objects.filter(curso=curso)
        pode_cursar=True
        if len(turmas)!=0:
            for turma in turmas:
                if (turma.idade_minima is not None and age < turma.idade_minima) or (turma.idade_maxima is not None and age > turma.idade_maxima):
                    teste = False
                    if not teste:
                        print('entrou aqui')
                        pode_cursar=False
                        teste=True
            
        #validação das informações do forms
        if form.is_valid() and pode_cursar:

cursos/templates/cadastro_camera.html
{% extends 'template.html' %}
{% load static %}
{% load bootstrap5 %}
{% block nav %}
{% include 'nav_cidade_inteligente.html' %}
{% endblock %}

{% block css %}
<link rel="stylesheet" href="/static/css/owl.carousel.min.css">
<link rel="stylesheet" href="/static/css/owl.theme.default.min.css">
<link rel="stylesheet" href="/static/css/cidade_inteligente_estilo.css">
{% endblock %}

{% block index %}
.s-nav-active
{% endblock %}

{% block main %}
<div id="main-carousel" class="row">
  <div class="col px-0">
    <div class="owl-carousel owl-theme">
      {% for item in carousel %}
      <div class="item">
        {% if item.url %}<a href="{{item.url}}">{% endif %}
          <img src="{{item.image.url}}" class="d-block w-100" alt="{{item.nome}}">
          {% if item.url %}</a>{% endif %}
      </div>
      {% endfor %}
    </div>
  </div>
</div>
<section  class="container">  
  <div class="row">
    <div class="col">
    <h2 class="mb-4">
      Programa Municipal de Vigilância Comunitária
    </h2>
    <div class="row">
      <div class="col px-4 text-justify">
        <p class="mb-3" style="text-indent: 0px;">
          Como participar:
        </p>
        <p class="mb-2">
          <strong>I</strong> – Disponibilidade de infraestrutura local dotada de câmeras fixas ou móveis,
          com resolução mínima em HD (High Definition) de 1 MPixel, voltadas para o
          logradouro público, cuja qualidade da imagem capturada seja capaz de
          identificar uma pessoa ou a licença (placa), modelo e cor de um veículo, tanto
          parados como em movimento, a pelo menos 30 (trinta) metros de distância, à
          luz do dia ou à noite.  
        </p>
        <p class="mb-2">
          <strong>II</strong> – O Sistema de Gerenciamento de Imagens da infraestrutura local (CFTV) do
          CONCEDENTE (DVR, NVR ou qualquer outro sistema de gerenciamento de
          imagem) deverá ser capaz de permitir o acesso
          tanto às imagens gravadas como às imagens em tempo real.
        </p>
        <p class="mb-2">
          <strong>III</strong> – A infraestrutura do CFTV ou VIDEOMONITORAMENTO do CONCEDENTE
          deve também ser provida de acessibilidade via INTERNET (protocolo TCP/IP) ou
          link dedicado com a Central de Operações Nova Friburgo Cidade Inteligente, e permitir
          através desta conexão, o acesso às imagens de todas as câmeras concedidas no sistema,
          gravadas ou em tempo real. No caso de imagem em tempo real, poderá ser através de
          acesso diretamente nas câmeras, ou através do sistema de gerenciamento de imagens
          (DVR, NVR ou outro sistema de gerenciamento de imagens).    
        </p>
        <p>
          (*) O link dedicado interligando a estrutura do CONCEDENTE à Central de
          Operações Nova Friburgo Cidade Inteligente para acesso às imagens será
          tratado à parte, conforme critérios que serão posteriormente definidos e
          propostos ao CONCEDENTE.
        </p>
        <p class="mt-5" style="text-align: left; text-indent: 0px;">
          EM CASOS DE DÚVIDAS ENTRE EM CONTATO COM A NOSSA EQUIPE QUE ENVIAREMOS TÉCNICOS PARA REALIZAR A INTEGRAÇÃO.
        </p>
        <p class="mt-4" style="text-align: left; text-indent: 0px;">
          Telefone da Central de Operações e Monitoramento - Nova Friburgo Cidade Inteligente
          (22) 2528-0091
        </p>
        <p class="mt-3" style="text-align: left; text-indent: 0px;">
          Nossas redes sociais:
        </p>
        <p style="text-align: left; text-indent: 0px;">
          Facebook: <a href="https://www.facebook.com/NFCidadeInteligente/" target="_blank">https://www.facebook.com/NFCidadeInteligente/</a>
        </p>
        <p style="text-align: left; text-indent: 0px;">
          Twitter: <a href="https://twitter.com/NovaFriburgoCI" target="_blank">https://twitter.com/NovaFriburgoCI</a>
        </p>
      </div>
      <div class="col">
        <h3>Formulário de Cadastro</h3>
        <form method="POST">
          {% csrf_token %}
          {% bootstrap_form form %}
          <button type="submit" class="btn btn-primary">Enviar</button>
        </form>
      </div>
    </div>
    </div>
  </div>
</section>
<style>
  .form-label{
    font-weight: bold;
  }
</style>
<!-- <h4>Perguntas Frequentes</h4> -->
<script>
    document.querySelector("#ver-detalhes").addEventListener("click", verMais)

  </script>
{% endblock %}

cursos/templates/footer.html
<footer class="row f-principal mt-auto" style="border-top: 1px solid rgb(184, 184, 184);">        
    <div class="col">
      <div class="row  pt-5 pb-4 mobile-flex-column footer-sup text-light">
        <div class="col d-flex flex-column justify-content-center">
          <img class="img-fluid logo m-auto" src="/static/images/logo_desenvolve_2.png" alt="">
          <p class="mx-auto mt-4 text-f">
            Av. Alberto Braune, 225 - Centro, Nova Friburgo - RJ, 28613-001<br>
            09:00 às 17:00 de Seg. à Sex. <br>
            (22) 2521-1558</p>
          <p class="mx-auto mt-4 text-light">
            <a class="text-light" target="_blank" href="https://www.facebook.com/desenvolvenf/">
              <i class="fa-brands fa-facebook me-4 mb-2"></i>
            </a>                
            <a class="text-light" target="_blank" href="https://www.instagram.com/desenvolvenf/">
              <i class="fa-brands fa-instagram me-4 mb-2"></i>
            </a>
          </p>
        </div>
        <div class="col d-flex justify-content-center">
          <div class="me-5">
            <p class="text-light pb-3 text-center">Plataformas</p>
            <ul>
              <li><a href="{% url 'cursos:home' %}">Capacitação Profissional</a></li>
              <li><a href="{% url 'cursos:cidade_inteligente' %}">Cidade Inteligente</a></li>
              <li><a href="#">Eventos</a></li>
              <li><a href="#">Finanças</a></li>
            </ul>
          </div>
          <div>
            <p class="text-light pb-3 text-center">Sistemas</p>
            <ul>
              <li><a href="#">Bem Estar Animal</a></li>
              <li><a href="https://casadotrabalhador.pmnf.rj.gov.br/">Casa do Trabalhador</a></li>
              <li><a href="#">Iluminação Pública</a></li>
              <li><a href="https://senhas.novafriburgo.rj.gov.br/login/?next=/">Senhas de Turismo</a></li>              
              <li><a href="https://culturanf.novafriburgo.rj.gov.br/">Mapeamento Cultural</a></li>
            </ul>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col text-center py-2 bg-f">
          <a href="#">
            &copy SUBSECRETARIA DE PLANEJAMENTO E DESENVOLVIMENTO ECONÔMICO - 2024.
          </a>
        </div>
      </div>
    </div>
</footer> 

cursos/templates/nav_cursos.html
<div id="navegacao" class="container">
  <div class="row">
    <div class="col d-flex justify-content-center flex-wrap">
      <a href="{% url 'cursos:home' %}" class="">
        <div class="d-flex flex-column align-items-center">
          <div
            id="s-index"
            class="s-nav rounded-circle {% block index %}{% endblock %}"
          ></div>
          <p class="text-dark">Início</p>
        </div>
      </a>
      <a href="{% url 'cursos:cursos_cevest' %}">
        <div class="d-flex flex-column align-items-center">
          <div id="s-cevest" class="s-nav rounded-circle"></div>
          <p class="text-dark">CEVEST</p>
        </div>
      </a>
      <a href="{% url 'cursos:cursos' %}">
        <div class="d-flex flex-column align-items-center">
          <div id="s-cursos" class="s-nav rounded-circle"></div>
          <p class="text-dark">Outros<br>Cursos</p>
        </div>
      </a>
      <a href="{% url 'cursos:cidade_inteligente' %}" class="">
        <div class="d-flex flex-column align-items-center">
          <div id="s-palestras" class="s-nav rounded-circle"></div>
          <p class="text-dark text-center">Cidade<br>Inteligente</p>
        </div>
      </a>
      <a href="{% url 'estagio:index' %}" class="me-2">
          <div class="d-flex flex-column align-items-center">
            <div id="s-estagio" class="s-nav rounded-circle"></div>
            <p class="text-dark text-center">Estágio</p>
          </div>
        </a>
      {% if request.user.is_authenticated %}
      <a href="{% url 'cursos:area_do_estudante' %}">
        <div class="d-flex flex-column align-items-center">
          <div id="s-estudante" class="s-nav rounded-circle"></div>
          <p class="text-dark text-center">Área do<br>estudante</p>
        </div>
      </a>
      {% endif %}
      <a href="{% url 'cursos:ensino_superior' %}" class="">
        <div class="d-flex flex-column align-items-center">
          <div id="s-en-superior" class="s-nav rounded-circle"></div>
          <p class="text-dark">En. Superior</p>
        </div>
      </a>
      <!-- <a href="{% url 'cursos:ensino_tecnico' %}" class="">
          <div class="d-flex flex-column align-items-center">
            <div id="s-en-tecnico" class="s-nav rounded-circle"></div>
            <p class="text-dark">En. Técnico</p>
          </div>
        </a>
        <a href="{% url 'cursos:curriculo_vitae' %}" class="">
          <div class="d-flex flex-column align-items-center">
            <div id="s-curriculo" class="s-nav rounded-circle"></div>
            <p class="text-dark text-center">Currículo<br>Vitae</p>
          </div>
        </a>   -->
      <!-- <a href="https://casadotrabalhador.pmnf.rj.gov.br/" class="">
        <div class="d-flex flex-column align-items-center">
          <div id="s-vaga" class="s-nav rounded-circle"></div>
          <p class="text-dark text-center">Casa do<br />Trabalhador</p>
        </div>
      </a> -->
      {% if request.user.is_staff %}
      <a href="{% url 'administrativo2' %}" class="">
        <div class="d-flex flex-column align-items-center">
          <div id="s-admin" class="s-nav rounded-circle destaque"></div>
          <p class="text-dark">Admin</p>
        </div>
      </a>
      {% endif %}
    </div>
  </div>
</div>
<style>
  #s-index {
    margin-right: 1rem !important;
    background-color: white !important;
    background-image: url(/static/images/icones/curso_home.png);
    background-size: contain;
  }
  #s-cevest {
    margin-right: 1rem !important;
    background-color: white !important;
    background-image: url(/static/images/icones/cursos_cevest.png);
    background-size: contain;
  }
  #s-cursos {
    margin-right: 1rem !important;
    background-color: white !important;
    background-image: url(/static/images/icones/curso_palestras.png);
    background-size: contain;
  }
  #s-palestras {
    margin-right: 1rem !important;
    background-color: white !important;
    background-image: url(/static/images/icones/curso_cursos.png);
    background-size: contain;    
  }
  #s-vaga {
    margin-right: 1rem !important;
    background-color: white !important;
    background-image: url(/static/images/icones/casa_do_trabalhador.png);
    background-size: contain;
  }
  #s-estudante {
    margin-right: 1rem !important;
    background-color: white !important;
    background-image: url(/static/images/icones/estudante.png);
    background-size: contain;
  }
  #s-en-superior {
    margin-right: 1rem !important;
    background-color: white !important;
    background-image: url(/static/images/icones/curso_superior.png);
    background-size: contain;
  }
  #s-en-tecnico {
    margin-right: 1rem !important;
    background-color: white !important;
    background-image: url(/static/images/icones/curso_tecnico.png);
    background-size: contain;
  }
  #s-curriculo {
    margin-right: 1rem !important;
    background-color: white !important;
    background-image: url(/static/images/icones/curso_curriculo.png);
    background-size: contain;
  }
  #s-estagio {
    margin-right: 1rem !important;
    background-color: white !important;
    background-image: url(/static/images/icones/curso_curriculo.png);
    background-size: contain;
  }
  #s-admin {
    margin-right: 1rem !important;
    background-color: white !important;
    background-image: url(/static/images/icones/curso_admin.png);
    background-size: contain;
  }
  #navegacao a p{
    margin-left: -1rem;
  }
</style>